# Generated by Django 5.1 on 2024-09-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
